services:
  - type: web
    name: sexta-do-almoco
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
